# Generated by Django 2.2.3 on 2019-09-17 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_cart_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='quantity',
            new_name='count',
        ),
    ]
