# Generated by Django 2.2.3 on 2019-09-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20190917_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
